# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  arm64-manylinux228:
     runs-on: ubuntu-24.04-arm
     strategy:
       fail-fast: false
       matrix:
         build-type: ["Python313", "Python312", "Python311"]
     container:
      image: pagmo2/manylinux228_aarch64_with_deps:latest
      env:
        PYGMO_BUILD_TYPE: ${{ matrix.build-type }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
     steps:
       - uses: actions/checkout@v4
       - name: Build
         run: bash tools/gha_manylinux.sh
  amd64-manylinux228:
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
         build-type: ["Python313", "Python312", "Python311"]
     container:
      image: pagmo2/manylinux228_x86_64_with_deps:latest
      env:
        PYGMO_BUILD_TYPE: ${{ matrix.build-type }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
     steps:
       - uses: actions/checkout@v4
       - name: Build
         run: bash tools/gha_manylinux.sh
  linux-x64:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14", "3.13", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pygmo
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
      - name: Build
        run: bash tools/gha_unix_nonmanylinux.sh
        shell: bash -l {0}
        env:
          PYGMO_PYTHON_VERSION: ${{ matrix.python-version }}
  linux-arm64:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pygmo
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
      - name: Build
        run: bash tools/gha_unix_nonmanylinux.sh
        shell: bash -l {0}
        env:
          PYGMO_PYTHON_VERSION: ${{ matrix.python-version }}
  macos-arm64:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pygmo
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
      - name: Build
        run: bash tools/gha_unix_nonmanylinux.sh
        shell: bash -l {0}
        env:
          PYGMO_PYTHON_VERSION: ${{ matrix.python-version }}
  windows-x64:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pygmo
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
      - name: Build
        run: .\tools\gha_windows.ps1
        shell: powershell
  build-and-deploydocs:
    if: ${{ github.event_name }} == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build 🔧 
        run: bash tools/gha_deploydocs.sh
      - name: Upload to github pages 🚀
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/_build/html # The folder the action should deploy.
